name: elite_guardians
description: A new Flutter application.

publish_to: 'none'

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.4
  progress_dialog_null_safe: ^1.0.7
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  url_launcher: ^6.1.5
  dio: ^4.0.6
  toast: ^0.3.0
  webview_flutter: ^3.0.4
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  path_provider: ^2.0.11
  flutter_polyline_points: ^1.0.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  google_maps_flutter: ^2.1.10
  google_places_picker: ^3.0.2
  stripe_payment: ^1.1.4
  flutter:
    sdk: flutter

  cupertino_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:

flutter:

  uses-material-design: true

  assets:
   - assets/images/ic_profile.png
   - assets/images/logo.png
   - assets/images/man_black.png
   - assets/images/woman_black.png
   - assets/images/intersex_black.png
   - assets/images/guardians.png
   - assets/images/home_car.png
   - assets/images/splash_new.png
   - assets/images/ic_car_black.png
   - assets/images/security_officer.png
